<?php
// Frontend/Core/SettingsView.php

require_once __DIR__ . '/View.php';

/**
 * SettingsView – data and actions for Frontend/ADMIN/settings.php.
 *
 * Handles:
 *   ?ajax=get_log         → JSON: return session activity log
 *   ?ajax=add_log  (POST) → JSON: append entry to session log
 *   ?ajax=clear_log       → JSON: clear log
 *   POST action=backup    → Stream SQL backup file download
 *   POST action=restore   → Process uploaded .sql restore file
 *
 * Usage:
 *   require_once '../../Frontend/Core/SettingsView.php';
 *   $view = new SettingsView();
 */
class SettingsView extends View
{
    public string $message = '';
    public string $msgType = '';

    public function __construct()
    {
        parent::__construct();
        $this->requireAdmin();

        // AJAX endpoints (no DB needed for log endpoints)
        if (isset($_GET['ajax'])) {
            $this->handleAjax();  // exits
        }

        // Form POST actions
        if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
            match ($_POST['action']) {
                'backup'  => $this->handleBackup(),   // exits (sends file)
                'restore' => $this->handleRestore(),  // sets message
                default   => null,
            };
        }
    }

    // ─────────────────────────────────────────────────────────────
    //  AJAX: session-based activity log
    // ─────────────────────────────────────────────────────────────

    private function handleAjax(): never
    {
        header('Content-Type: application/json');

        if (!isset($_SESSION['activity_log'])) {
            $_SESSION['activity_log'] = [];
        }

        $action = $_GET['ajax'];

        if ($action === 'get_log') {
            echo json_encode(['log' => array_slice($_SESSION['activity_log'], 0, 30)]);
            exit();
        }

        if ($action === 'add_log' && isset($_POST['type'], $_POST['msg'])) {
            $entry = [
                'type' => preg_replace('/[^a-z_]/', '', $_POST['type']),
                'msg'  => substr(strip_tags($_POST['msg']), 0, 200),
                'user' => htmlspecialchars(Session::get('user', 'Admin')),
                'time' => date('M j, Y g:i A'),
                'ts'   => time(),
            ];
            array_unshift($_SESSION['activity_log'], $entry);
            $_SESSION['activity_log'] = array_slice($_SESSION['activity_log'], 0, 30);
            echo json_encode(['ok' => true]);
            exit();
        }

        if ($action === 'clear_log') {
            $_SESSION['activity_log'] = [];
            echo json_encode(['ok' => true]);
            exit();
        }

        echo json_encode(['ok' => false, 'message' => 'Unknown action']);
        exit();
    }

    // ─────────────────────────────────────────────────────────────
    //  Backup – stream .sql file to browser
    // ─────────────────────────────────────────────────────────────

    private function handleBackup(): never
    {
        $tables = [];
        $res    = $this->db->query('SHOW TABLES');
        while ($row = $res->fetch_array()) {
            $tables[] = $row[0];
        }

        $adminUser = htmlspecialchars(Session::get('user', 'Admin'));
        $sql  = "-- =============================================\n";
        $sql .= "-- Empress' Cafe Database Backup\n";
        $sql .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by: $adminUser\n";
        $sql .= "-- =============================================\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        foreach ($tables as $table) {
            $sql .= "-- -------------------------------------------\n";
            $sql .= "-- Table structure for `$table`\n";
            $sql .= "-- -------------------------------------------\n";
            $sql .= "DROP TABLE IF EXISTS `$table`;\n";

            $createRes = $this->db->query("SHOW CREATE TABLE `$table`");
            $createRow = $createRes->fetch_assoc();
            $sql .= $createRow['Create Table'] . ";\n\n";

            $dataRes   = $this->db->query("SELECT * FROM `$table`");
            $numFields = $dataRes->field_count;
            $numRows   = $dataRes->num_rows;

            if ($numRows > 0) {
                $sql .= "-- Data for table `$table`\n";
                while ($dataRow = $dataRes->fetch_row()) {
                    $sql .= "INSERT INTO `$table` VALUES(";
                    for ($i = 0; $i < $numFields; $i++) {
                        $sql .= ($dataRow[$i] === null)
                            ? 'NULL'
                            : "'" . $this->db->real_escape_string($dataRow[$i]) . "'";
                        if ($i < $numFields - 1) $sql .= ',';
                    }
                    $sql .= ");\n";
                }
                $sql .= "\n";
            }
        }

        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

        $filename = 'empress_cafe_backup_' . date('Ymd_His') . '.sql';

        $this->logActivity('backup', "Database backup downloaded: $filename");

        header('Content-Type: application/octet-stream');
        header("Content-Disposition: attachment; filename=\"$filename\"");
        header('Content-Length: ' . strlen($sql));
        echo $sql;
        exit();
    }

    // ─────────────────────────────────────────────────────────────
    //  Restore – execute uploaded .sql file
    // ─────────────────────────────────────────────────────────────

    private function handleRestore(): void
    {
        if (
            !isset($_FILES['backup_file']) ||
            $_FILES['backup_file']['error'] !== UPLOAD_ERR_OK
        ) {
            $this->message = 'No file uploaded or upload error.';
            $this->msgType = 'danger';
            return;
        }

        $ext = strtolower(pathinfo($_FILES['backup_file']['name'], PATHINFO_EXTENSION));
        if ($ext !== 'sql') {
            $this->message = 'Invalid file type. Please upload a .sql file.';
            $this->msgType = 'danger';
            return;
        }

        $sqlContent = file_get_contents($_FILES['backup_file']['tmp_name']);
        if (empty($sqlContent)) {
            $this->message = 'Uploaded file is empty. Please upload a valid backup file.';
            $this->msgType = 'danger';
            return;
        }

        $this->db->query('SET FOREIGN_KEY_CHECKS=0');

        // Strip comment lines and split on statement-ending semicolons
        $lines      = explode("\n", $sqlContent);
        $filtered   = array_filter($lines, fn($l) => strpos(trim($l), '--') !== 0);
        $cleanSql   = implode("\n", $filtered);
        $statements = array_filter(
            array_map('trim', preg_split('/;\s*/m', $cleanSql)),
            fn($s) => !empty($s)
        );

        $errors = 0;
        foreach ($statements as $stmt) {
            $upper = strtoupper(trim($stmt));
            if (strpos($upper, 'SET FOREIGN_KEY_CHECKS') === 0) {
                continue;
            }
            // Rewrite CREATE TABLE to avoid errors on already-existing tables
            $stmt = preg_replace('/^CREATE TABLE\s+`/i', 'CREATE TABLE IF NOT EXISTS `', $stmt);

            if (!$this->db->query($stmt)) {
                if ($this->db->errno !== 1062) { // ignore duplicate-entry errors
                    $errors++;
                }
            }
        }

        $this->db->query('SET FOREIGN_KEY_CHECKS=1');

        if ($errors === 0) {
            $this->message = 'Database restored successfully! All data has been recovered.';
            $this->msgType = 'success';
            $this->logActivity('restore', 'Database restored successfully');
        } else {
            $this->message = "Restore completed with $errors error(s). Most data may have been recovered. Check database manually if needed.";
            $this->msgType = 'warning';
            $this->logActivity('restore_warn', "Restore completed with $errors error(s)");
        }
    }

    // ─────────────────────────────────────────────────────────────
    //  Helper
    // ─────────────────────────────────────────────────────────────

    private function logActivity(string $type, string $msg): void
    {
        if (!isset($_SESSION['activity_log'])) {
            $_SESSION['activity_log'] = [];
        }
        array_unshift($_SESSION['activity_log'], [
            'type' => $type,
            'msg'  => $msg,
            'user' => htmlspecialchars(Session::get('user', 'Admin')),
            'time' => date('M j, Y g:i A'),
            'ts'   => time(),
        ]);
        $_SESSION['activity_log'] = array_slice($_SESSION['activity_log'], 0, 30);
    }
}
