<?php
session_start();
if (!isset($_SESSION['user'])) {
    header("Location: ../../Frontend/lockscreen.html");
    exit();
}

require_once '../../Backend/conn.php';

$message = '';
$msgType = '';

// ── Handle Backup Download ─────────────────────────────────────
if (isset($_POST['action']) && $_POST['action'] === 'backup') {
    $tables = [];
    $result = $conn->query("SHOW TABLES");
    while ($row = $result->fetch_array()) {
        $tables[] = $row[0];
    }

    $sql = "-- =============================================\n";
    $sql .= "-- Empress' Cafe Database Backup\n";
    $sql .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
    $sql .= "-- Generated by: " . htmlspecialchars($_SESSION['user']) . "\n";
    $sql .= "-- =============================================\n\n";
    $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $table) {
        // Structure
        $sql .= "-- -------------------------------------------\n";
        $sql .= "-- Table structure for `$table`\n";
        $sql .= "-- -------------------------------------------\n";
        $sql .= "DROP TABLE IF EXISTS `$table`;\n";
        $createResult = $conn->query("SHOW CREATE TABLE `$table`");
        $createRow = $createResult->fetch_assoc();
        $sql .= $createRow['Create Table'] . ";\n\n";

        // Data
        $dataResult = $conn->query("SELECT * FROM `$table`");
        $numFields = $dataResult->field_count;
        $numRows = $dataResult->num_rows;

        if ($numRows > 0) {
            $sql .= "-- Data for table `$table`\n";
            while ($dataRow = $dataResult->fetch_row()) {
                $sql .= "INSERT INTO `$table` VALUES(";
                for ($i = 0; $i < $numFields; $i++) {
                    if ($dataRow[$i] === null) {
                        $sql .= "NULL";
                    } else {
                        $sql .= "'" . $conn->real_escape_string($dataRow[$i]) . "'";
                    }
                    if ($i < $numFields - 1) $sql .= ",";
                }
                $sql .= ");\n";
            }
            $sql .= "\n";
        }
    }

    $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

    $filename = 'empress_cafe_backup_' . date('Ymd_His') . '.sql';
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($sql));
    echo $sql;
    exit();
}

// ── Handle Restore Upload ──────────────────────────────────────
if (isset($_POST['action']) && $_POST['action'] === 'restore') {
    if (isset($_FILES['backup_file']) && $_FILES['backup_file']['error'] === UPLOAD_ERR_OK) {
        $ext = strtolower(pathinfo($_FILES['backup_file']['name'], PATHINFO_EXTENSION));
        if ($ext !== 'sql') {
            $message = 'Invalid file type. Please upload a .sql file.';
            $msgType = 'danger';
        } else {
            $sqlContent = file_get_contents($_FILES['backup_file']['tmp_name']);
            if (empty($sqlContent)) {
                $message = 'Uploaded file is empty. Please upload a valid backup file.';
                $msgType = 'danger';
            } else {
                // Split and execute statements
                $conn->query("SET FOREIGN_KEY_CHECKS=0");

                // Remove comment lines, then split on statement-ending semicolons
                $lines = explode("\n", $sqlContent);
                $filteredLines = array_filter($lines, fn($line) => strpos(trim($line), '--') !== 0);
                $cleanSql = implode("\n", $filteredLines);

                // Split on semicolons followed by optional whitespace/newlines
                $statements = array_filter(
                    array_map('trim', preg_split('/;\s*/m', $cleanSql)),
                    fn($s) => !empty($s)
                );

                $errors = 0;
                foreach ($statements as $stmt) {
                    $upperStmt = strtoupper(trim($stmt));
                    // Skip SET FOREIGN_KEY_CHECKS lines (we handle them manually)
                    if (strpos($upperStmt, 'SET FOREIGN_KEY_CHECKS') === 0) {
                        continue;
                    }
                    // For CREATE TABLE statements, rewrite to use IF NOT EXISTS
                    // so tables that already exist are skipped rather than erroring
                    $stmt = preg_replace('/^CREATE TABLE\s+`/i', 'CREATE TABLE IF NOT EXISTS `', $stmt);
                    if (!$conn->query($stmt)) {
                        // Ignore duplicate entry errors (1062) during INSERT — data already there
                        if ($conn->errno !== 1062) {
                            $errors++;
                        }
                    }
                }
                $conn->query("SET FOREIGN_KEY_CHECKS=1");

                if ($errors === 0) {
                    $message = 'Database restored successfully! All data has been recovered.';
                    $msgType = 'success';
                } else {
                    $message = "Restore completed with $errors error(s). Most data may have been recovered. Check database manually if needed.";
                    $msgType = 'warning';
                }
            }
        }
    } else {
        $message = 'No file uploaded or upload error occurred. Please try again.';
        $msgType = 'danger';
    }
}

// ── Fetch backup history from session log ─────────────────────
if (!isset($_SESSION['backup_log'])) $_SESSION['backup_log'] = [];
if (isset($_POST['action']) && $_POST['action'] === 'backup') {
    // Won't reach here due to exit above, but log is updated in JS
}

$conn->close();
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OPERLYTICS | Settings</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link rel="stylesheet" href="../plugins/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="../plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <link rel="stylesheet" href="../dist/css/adminlte.min.css">
  <link rel="stylesheet" href="../dist/css/empress-cafe-theme.css">
  <style>
    body, .main-header.navbar { transition: background-color .5s ease, color .5s ease; }
    #darkModeToggle           { transition: box-shadow .3s ease; }
    #darkModeToggle i         { transition: transform .3s ease; }
    #darkModeToggle.clicked   { box-shadow: 0 0 15px rgba(255,255,255,.8); }
    #darkModeToggle.clicked i { transform: rotate(180deg) scale(1.2); }

    /* Settings Cards */
    .settings-section-title {
      font-size: 0.75rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: #aaa;
      margin-bottom: 12px;
      margin-top: 8px;
    }

    .backup-icon-wrap {
      width: 60px;
      height: 60px;
      border-radius: 16px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 1.6rem;
      margin-right: 16px;
      flex-shrink: 0;
    }
    .backup-icon-wrap.green  { background: rgba(40,167,69,.15);  color: #28a745; }
    .backup-icon-wrap.blue   { background: rgba(23,162,184,.15); color: #17a2b8; }
    .backup-icon-wrap.yellow { background: rgba(255,193,7,.15);  color: #ffc107; }
    .backup-icon-wrap.pink   { background: rgba(233,30,140,.15); color: #e91e8c; }

    .action-card {
      border-radius: 12px;
      border: none;
      transition: transform .2s, box-shadow .2s;
    }
    .action-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 24px rgba(0,0,0,.25) !important;
    }

    /* Drop zone */
    #dropZone {
      border: 2px dashed #444;
      border-radius: 12px;
      padding: 32px;
      text-align: center;
      cursor: pointer;
      transition: border-color .2s, background .2s;
    }
    #dropZone.dragover {
      border-color: #17a2b8;
      background: rgba(23,162,184,.07);
    }
    #dropZone i { font-size: 2.5rem; color: #666; margin-bottom: 8px; display: block; }

    /* Progress bar animation */
    .backup-progress { display: none; }
    @keyframes pulse-bar {
      0%   { opacity: 1; }
      50%  { opacity: .5; }
      100% { opacity: 1; }
    }
    .progress-bar.animated-pulse { animation: pulse-bar 1s infinite; }

    /* Timeline for backup history */
    .backup-timeline .item {
      display: flex;
      align-items: center;
      padding: 10px 0;
      border-bottom: 1px solid rgba(255,255,255,.06);
    }
    .backup-timeline .item:last-child { border-bottom: none; }
    .backup-timeline .item .dot {
      width: 10px; height: 10px;
      border-radius: 50%;
      margin-right: 12px;
      flex-shrink: 0;
    }
    .dot-success { background: #28a745; }
    .dot-restore { background: #17a2b8; }
  </style>
</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">

  <!-- ── Navbar ─────────────────────────────────────────────── -->
  <nav class="main-header navbar navbar-expand navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index2.php" class="nav-link">Home</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button"><i class="fas fa-expand-arrows-alt"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="darkModeToggle" href="#" role="button"><i class="fas fa-moon"></i></a>
      </li>
    </ul>
  </nav>

  <!-- ── Sidebar ───────────────────────────────────────────── -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="#" class="brand-link">
      <img src="../dist/img/Empress' Cafe Boracay.jpg" alt="Logo" class="brand-image img-circle elevation-3" style="opacity:.8">
      <span class="brand-text font-weight-light">Empress' Cafe</span>
    </a>
    <div class="sidebar">
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image"><img src="../dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"></div>
        <div class="info">
          <a href="#" class="d-block"><?= htmlspecialchars($_SESSION['user'] ?? 'Admin') ?></a>
        </div>
      </div>
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item"><a href="./index2.php"          class="nav-link"><i class="nav-icon fas fa-tachometer-alt"></i><p>Overview</p></a></li>
          <li class="nav-item"><a href="./menu-management.php" class="nav-link"><i class="nav-icon fas fa-utensils"></i><p>Menu Management</p></a></li>
          <li class="nav-item"><a href="./inventory.php"       class="nav-link"><i class="nav-icon fas fa-boxes"></i><p>Inventory Tracking</p></a></li>
          <li class="nav-item"><a href="./suppliers.php"       class="nav-link"><i class="nav-icon fas fa-truck"></i><p>Supplier Info</p></a></li>
          <li class="nav-item"><a href="./staff-list.php"      class="nav-link"><i class="far fa-user nav-icon"></i><p>Staff List</p></a></li>
          <li class="nav-item"><a href="./sale_revenue.php"    class="nav-link"><i class="nav-icon fas fa-chart-line"></i><p>Sales &amp; Revenue</p></a></li>
          <li class="nav-item"><a href="./report.php"          class="nav-link"><i class="nav-icon fas fa-file-alt"></i><p>Reports</p></a></li>
          <li class="nav-item"><a href="./settings.php"        class="nav-link active"><i class="nav-icon fas fa-cog"></i><p>Settings</p></a></li>
          <li class="nav-item mt-auto"><a href="../../Backend/logout.php" class="nav-link"><i class="nav-icon fas fa-sign-out-alt"></i><p>Log Out</p></a></li>
        </ul>
      </nav>
    </div>
  </aside>

  <!-- ── Content Wrapper ───────────────────────────────────── -->
  <div class="content-wrapper">
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><i class="fas fa-cog mr-2"></i>Settings</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="index2.php">Home</a></li>
              <li class="breadcrumb-item active">Settings</li>
            </ol>
          </div>
        </div>
      </div>
    </div>

    <section class="content">
      <div class="container-fluid">

        <!-- ── Alert Messages ──────────────────────────────── -->
        <?php if ($message): ?>
        <div class="alert alert-<?= $msgType ?> alert-dismissible fade show" role="alert">
          <i class="fas fa-<?= $msgType === 'success' ? 'check-circle' : ($msgType === 'danger' ? 'times-circle' : 'exclamation-triangle') ?> mr-2"></i>
          <?= htmlspecialchars($message) ?>
          <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
        </div>
        <?php endif; ?>

        <!-- ── BACKUP & RESTORE SECTION ────────────────────── -->
        <div class="settings-section-title"><i class="fas fa-database mr-1"></i> Data Backup &amp; Restore</div>

        <div class="row">

          <!-- Backup Card -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card action-card elevation-2 h-100">
              <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                  <div class="backup-icon-wrap green">
                    <i class="fas fa-download"></i>
                  </div>
                  <div>
                    <h5 class="mb-0 font-weight-bold">Download Backup</h5>
                    <small class="text-muted">Export full database as .sql file</small>
                  </div>
                </div>
                <p class="text-muted small mb-3">
                  Back up all your data — orders, menu, inventory, staff, suppliers, and reports.
                  Save it to your computer to keep your data safe.
                </p>

                <!-- Progress bar (shown during backup) -->
                <div class="backup-progress mb-3" id="backupProgress">
                  <div class="progress" style="height:6px; border-radius:4px;">
                    <div class="progress-bar bg-success animated-pulse" style="width:100%"></div>
                  </div>
                  <small class="text-muted mt-1 d-block text-center">Generating backup file…</small>
                </div>

                <form method="POST" id="backupForm">
                  <input type="hidden" name="action" value="backup">
                  <button type="submit" class="btn btn-success btn-block" id="backupBtn" onclick="startBackup()">
                    <i class="fas fa-download mr-2"></i>Download Backup Now
                  </button>
                </form>
              </div>
              <div class="card-footer" style="background:rgba(40,167,69,.07); border-top:1px solid rgba(40,167,69,.15);">
                <small class="text-muted"><i class="fas fa-info-circle mr-1"></i>
                  Recommended: backup weekly or before any major changes.
                </small>
              </div>
            </div>
          </div>

          <!-- Restore Card -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card action-card elevation-2 h-100">
              <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                  <div class="backup-icon-wrap blue">
                    <i class="fas fa-upload"></i>
                  </div>
                  <div>
                    <h5 class="mb-0 font-weight-bold">Restore Backup</h5>
                    <small class="text-muted">Import a previous .sql backup file</small>
                  </div>
                </div>
                <p class="text-muted small mb-3">
                  If data is lost or something goes wrong, upload your backup file to recover everything.
                </p>

                <form method="POST" enctype="multipart/form-data" id="restoreForm" onsubmit="return confirmRestore()">
                  <input type="hidden" name="action" value="restore">

                  <!-- Drop Zone -->
                  <div id="dropZone" onclick="document.getElementById('backupFile').click()">
                    <i class="fas fa-cloud-upload-alt"></i>
                    <div id="dropText">
                      <strong>Click or drag &amp; drop</strong><br>
                      <small class="text-muted">your .sql backup file here</small>
                    </div>
                    <div id="fileChosen" class="text-info mt-2" style="display:none;">
                      <i class="fas fa-file-code mr-1"></i><span id="chosenName"></span>
                    </div>
                  </div>
                  <input type="file" name="backup_file" id="backupFile" accept=".sql" style="display:none;" onchange="fileSelected(this)">

                  <button type="submit" class="btn btn-info btn-block mt-3" id="restoreBtn" disabled>
                    <i class="fas fa-redo mr-2"></i>Restore Database
                  </button>
                </form>
              </div>
              <div class="card-footer" style="background:rgba(23,162,184,.07); border-top:1px solid rgba(23,162,184,.15);">
                <small class="text-warning"><i class="fas fa-exclamation-triangle mr-1"></i>
                  Warning: This will overwrite current data. Make sure to backup first!
                </small>
              </div>
            </div>
          </div>

          <!-- Tips Card -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card action-card elevation-2 h-100">
              <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                  <div class="backup-icon-wrap yellow">
                    <i class="fas fa-lightbulb"></i>
                  </div>
                  <div>
                    <h5 class="mb-0 font-weight-bold">Backup Tips</h5>
                    <small class="text-muted">Best practices for data safety</small>
                  </div>
                </div>
                <ul class="list-unstyled small text-muted mb-0">
                  <li class="mb-2"><i class="fas fa-check-circle text-success mr-2"></i>Back up <strong>every week</strong> or before any updates</li>
                  <li class="mb-2"><i class="fas fa-check-circle text-success mr-2"></i>Save the .sql file to <strong>Google Drive or USB</strong></li>
                  <li class="mb-2"><i class="fas fa-check-circle text-success mr-2"></i>Always back up <strong>before restoring</strong> to stay safe</li>
                  <li class="mb-2"><i class="fas fa-check-circle text-success mr-2"></i>The backup file is <strong>confidential</strong> — do not share it</li>
                  <li class="mb-2"><i class="fas fa-check-circle text-success mr-2"></i>I-check ang filename — format: <code>empress_cafe_backup_YYYYMMDD.sql</code></li>
                </ul>
              </div>
              <div class="card-footer" style="background:rgba(255,193,7,.07); border-top:1px solid rgba(255,193,7,.15);">
                <small class="text-muted"><i class="fas fa-shield-alt mr-1 text-warning"></i>
                  Your backup contains all sensitive business data.
                </small>
              </div>
            </div>
          </div>

        </div><!-- end row -->

        <!-- ── Backup History (session-based) ──────────────── -->
        <div class="settings-section-title mt-2"><i class="fas fa-history mr-1"></i> Activity Log</div>
        <div class="row">
          <div class="col-md-8 mb-4">
            <div class="card elevation-2" style="border-radius:12px; border:none;">
              <div class="card-header d-flex align-items-center justify-content-between">
                <h6 class="mb-0"><i class="fas fa-list-alt mr-2"></i>Recent Backup / Restore Activity</h6>
                <button class="btn btn-sm btn-outline-secondary" onclick="clearLog()">
                  <i class="fas fa-trash-alt mr-1"></i>Clear Log
                </button>
              </div>
              <div class="card-body">
                <div class="backup-timeline" id="activityLog">
                  <div class="text-muted text-center py-3" id="emptyLog">
                    <i class="fas fa-inbox fa-2x mb-2 d-block" style="color:#444;"></i>
                    No activity yet. Click "Download Backup" to get started.
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- ── APPEARANCE SETTINGS ──────────────── -->
          <div class="col-md-4 mb-4">
            <div class="card elevation-2" style="border-radius:12px; border:none;">
              <div class="card-header">
                <h6 class="mb-0"><i class="fas fa-palette mr-2"></i>Appearance</h6>
              </div>
              <div class="card-body">
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <div>
                    <strong>Dark Mode</strong><br>
                    <small class="text-muted">Toggle dark/light theme</small>
                  </div>
                  <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="darkModeSwitch" onchange="toggleDarkMode(this)">
                    <label class="custom-control-label" for="darkModeSwitch"></label>
                  </div>
                </div>
                <hr style="border-color:rgba(255,255,255,.08);">
                <div class="d-flex align-items-center justify-content-between">
                  <div>
                    <strong>Current User</strong><br>
                    <small class="text-muted">Logged in as</small>
                  </div>
                  <span class="badge badge-pink p-2">
                    <i class="fas fa-user mr-1"></i><?= htmlspecialchars($_SESSION['user'] ?? 'Admin') ?>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div><!-- /.container-fluid -->
    </section>
  </div><!-- /.content-wrapper -->

</div><!-- /.wrapper -->

<!-- ── Confirm Restore Modal ─────────────────────────────────── -->
<div class="modal fade" id="confirmRestoreModal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="border-radius:16px; border:none;">
      <div class="modal-header" style="background:rgba(220,53,69,.1); border-bottom:1px solid rgba(220,53,69,.2); border-radius:16px 16px 0 0;">
        <h5 class="modal-title text-danger"><i class="fas fa-exclamation-triangle mr-2"></i>Confirm Restore</h5>
        <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <p class="mb-2"><strong>Are you sure you want to restore?</strong></p>
        <p class="text-muted small">
          This action will <strong>overwrite all current data</strong> with your backup file.
          This cannot be undone unless you have a new backup.
        </p>
        <div class="alert alert-warning py-2 small">
          <i class="fas fa-save mr-1"></i>
          <strong>Tip:</strong> Download the current backup before restoring!
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="proceedRestore()">
          <i class="fas fa-redo mr-1"></i>Yes, Restore Now
        </button>
      </div>
    </div>
  </div>
</div>

<!-- ── Scripts ──────────────────────────────────────────────── -->
<script src="../plugins/jquery/jquery.min.js"></script>
<script src="../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="../dist/js/adminlte.js"></script>

<script>
// ── Dark Mode ──────────────────────────────────────────────────
$(function () {
  var dm = localStorage.getItem('darkMode');
  var isDark = dm !== 'false';
  applyDarkMode(isDark);
  $('#darkModeSwitch').prop('checked', isDark);

  $('#darkModeToggle').on('click', function (e) {
    e.preventDefault();
    var nowDark = $('body').hasClass('dark-mode');
    applyDarkMode(!nowDark);
    $('#darkModeSwitch').prop('checked', !nowDark);
    localStorage.setItem('darkMode', !nowDark);
    $(this).addClass('clicked');
    setTimeout(() => $(this).removeClass('clicked'), 300);
  });
});

function applyDarkMode(enable) {
  if (enable) {
    $('body').addClass('dark-mode');
    $('.main-header.navbar').addClass('navbar-dark').removeClass('navbar-white navbar-light bg-white');
    $('#darkModeToggle i').removeClass('fa-moon').addClass('fa-sun');
    localStorage.setItem('darkMode', 'true');
  } else {
    $('body').removeClass('dark-mode');
    $('.main-header.navbar').removeClass('navbar-dark').addClass('navbar-white navbar-light bg-white');
    $('#darkModeToggle i').removeClass('fa-sun').addClass('fa-moon');
    localStorage.setItem('darkMode', 'false');
  }
}

function toggleDarkMode(el) {
  applyDarkMode(el.checked);
}

// ── Drag & Drop ────────────────────────────────────────────────
var dropZone = document.getElementById('dropZone');
dropZone.addEventListener('dragover', function(e) {
  e.preventDefault();
  dropZone.classList.add('dragover');
});
dropZone.addEventListener('dragleave', function() {
  dropZone.classList.remove('dragover');
});
dropZone.addEventListener('drop', function(e) {
  e.preventDefault();
  dropZone.classList.remove('dragover');
  var file = e.dataTransfer.files[0];
  if (file) {
    var dt = new DataTransfer();
    dt.items.add(file);
    document.getElementById('backupFile').files = dt.files;
    fileSelected({ files: [file] });
  }
});

function fileSelected(input) {
  var file = input.files[0];
  if (file) {
    document.getElementById('chosenName').textContent = file.name;
    document.getElementById('dropText').style.display = 'none';
    document.getElementById('fileChosen').style.display = 'block';
    document.getElementById('restoreBtn').disabled = false;
  }
}

// ── Restore Confirm ────────────────────────────────────────────
function confirmRestore() {
  $('#confirmRestoreModal').modal('show');
  return false;
}

function proceedRestore() {
  $('#confirmRestoreModal').modal('hide');
  addLog('restore', 'Restore initiated from backup file');
  document.getElementById('restoreForm').submit();
}

// ── Backup progress animation ──────────────────────────────────
function startBackup() {
  // Show progress UI after a short delay so the form submission fires first
  setTimeout(function() {
    document.getElementById('backupProgress').style.display = 'block';
    document.getElementById('backupBtn').innerHTML = '<i class="fas fa-spinner fa-spin mr-2"></i>Generating…';
  }, 100);
  addLog('backup', 'Database backup downloaded');
  setTimeout(function() {
    document.getElementById('backupProgress').style.display = 'none';
    document.getElementById('backupBtn').innerHTML = '<i class="fas fa-download mr-2"></i>Download Backup Now';
  }, 3500);
}

// ── Activity Log ───────────────────────────────────────────────
var LOG_KEY = 'empress_backup_log';

function getLog() {
  try { return JSON.parse(localStorage.getItem(LOG_KEY)) || []; }
  catch(e) { return []; }
}

function saveLog(log) {
  localStorage.setItem(LOG_KEY, JSON.stringify(log.slice(-20))); // keep last 20
}

function addLog(type, msg) {
  var log = getLog();
  log.unshift({
    type: type,
    msg: msg,
    time: new Date().toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' })
  });
  saveLog(log);
  renderLog();
}

function renderLog() {
  var log = getLog();
  var container = document.getElementById('activityLog');
  var empty = document.getElementById('emptyLog');
  if (log.length === 0) {
    empty.style.display = 'block';
    return;
  }
  empty.style.display = 'none';

  // Remove old items (keep empty div)
  var oldItems = container.querySelectorAll('.item');
  oldItems.forEach(function(el) { el.remove(); });

  log.forEach(function(entry) {
    var div = document.createElement('div');
    div.className = 'item';
    var dotClass = entry.type === 'backup' ? 'dot-success' : 'dot-restore';
    var icon = entry.type === 'backup' ? 'fa-download text-success' : 'fa-upload text-info';
    div.innerHTML =
      '<div class="dot ' + dotClass + '"></div>' +
      '<div class="flex-grow-1">' +
        '<strong><i class="fas ' + icon + ' mr-1"></i>' + escHtml(entry.msg) + '</strong>' +
        '<br><small class="text-muted">' + escHtml(entry.time) + '</small>' +
      '</div>';
    container.insertBefore(div, container.querySelector('.item') || empty);
  });
}

function clearLog() {
  localStorage.removeItem(LOG_KEY);
  renderLog();
}

function escHtml(t) {
  return t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

// ── Init on load ───────────────────────────────────────────────
$(function() {
  renderLog();

  // Show restore result in log if message exists
  <?php if ($message && $msgType === 'success'): ?>
  addLog('restore', 'Database restored successfully');
  <?php elseif ($message && $msgType === 'warning'): ?>
  addLog('restore', 'Restore completed with warnings');
  <?php elseif ($message && $msgType === 'danger'): ?>
  addLog('restore', 'Restore failed — <?= addslashes(htmlspecialchars($message)) ?>');
  <?php endif; ?>
});
</script>
</body>
</html>